# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_AccessDb', [dirname(__file__)])
        except ImportError:
            import _AccessDb
            return _AccessDb
        if fp is not None:
            try:
                _mod = imp.load_module('_AccessDb', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _AccessDb = swig_import_helper()
    del swig_import_helper
else:
    import _AccessDb
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class AccessDb:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AccessDb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AccessDb, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _AccessDb.new_AccessDb(*args)
        try: self.this.append(this)
        except: self.this = this
    def Download(self): return _AccessDb.AccessDb_Download(self)
    def Check(self): return _AccessDb.AccessDb_Check(self)
    def Upload(self): return _AccessDb.AccessDb_Upload(self)
    def setReferenceRun(self, *args): return _AccessDb.AccessDb_setReferenceRun(self, *args)
    def setFecVersionMajorId(self, *args): return _AccessDb.AccessDb_setFecVersionMajorId(self, *args)
    def setFecVersionMinorId(self, *args): return _AccessDb.AccessDb_setFecVersionMinorId(self, *args)
    def setFedVersionMajorId(self, *args): return _AccessDb.AccessDb_setFedVersionMajorId(self, *args)
    def setFedVersionMinorId(self, *args): return _AccessDb.AccessDb_setFedVersionMinorId(self, *args)
    def setConnectionVersionMajorId(self, *args): return _AccessDb.AccessDb_setConnectionVersionMajorId(self, *args)
    def setConnectionVersionMinorId(self, *args): return _AccessDb.AccessDb_setConnectionVersionMinorId(self, *args)
    def setDcuInfoVersionMajorId(self, *args): return _AccessDb.AccessDb_setDcuInfoVersionMajorId(self, *args)
    def setDcuInfoVersionMinorId(self, *args): return _AccessDb.AccessDb_setDcuInfoVersionMinorId(self, *args)
    def setDcuPsuMapVersionMajorId(self, *args): return _AccessDb.AccessDb_setDcuPsuMapVersionMajorId(self, *args)
    def setDcuPsuMapVersionMinorId(self, *args): return _AccessDb.AccessDb_setDcuPsuMapVersionMinorId(self, *args)
    def setAnalysisVersionMapPointerId(self, *args): return _AccessDb.AccessDb_setAnalysisVersionMapPointerId(self, *args)
    def setMaskVersionMajorId(self, *args): return _AccessDb.AccessDb_setMaskVersionMajorId(self, *args)
    def setMaskVersionMinorId(self, *args): return _AccessDb.AccessDb_setMaskVersionMinorId(self, *args)
    def setDownloadFec(self, *args): return _AccessDb.AccessDb_setDownloadFec(self, *args)
    def setDownloadFed(self, *args): return _AccessDb.AccessDb_setDownloadFed(self, *args)
    def setDownloadConnection(self, *args): return _AccessDb.AccessDb_setDownloadConnection(self, *args)
    def setDownloadPsu(self, *args): return _AccessDb.AccessDb_setDownloadPsu(self, *args)
    def setDownloadDetId(self, *args): return _AccessDb.AccessDb_setDownloadDetId(self, *args)
    def setCheckBadPll(self, *args): return _AccessDb.AccessDb_setCheckBadPll(self, *args)
    def setCheckMissingDevices(self, *args): return _AccessDb.AccessDb_setCheckMissingDevices(self, *args)
    def setCheckMissingFedChannels(self, *args): return _AccessDb.AccessDb_setCheckMissingFedChannels(self, *args)
    def setCheckFedConnection(self, *args): return _AccessDb.AccessDb_setCheckFedConnection(self, *args)
    def setStripListName(self, *args): return _AccessDb.AccessDb_setStripListName(self, *args)
    def setDisableStrips(self, *args): return _AccessDb.AccessDb_setDisableStrips(self, *args)
    def setUploadFeds(self, *args): return _AccessDb.AccessDb_setUploadFeds(self, *args)
    def setUploadFecs(self, *args): return _AccessDb.AccessDb_setUploadFecs(self, *args)
    def setUploadConnections(self, *args): return _AccessDb.AccessDb_setUploadConnections(self, *args)
    def setPartition(self, *args): return _AccessDb.AccessDb_setPartition(self, *args)
    def getReferenceRun(self): return _AccessDb.AccessDb_getReferenceRun(self)
    def getFecVersionMajorId(self): return _AccessDb.AccessDb_getFecVersionMajorId(self)
    def getFecVersionMinorId(self): return _AccessDb.AccessDb_getFecVersionMinorId(self)
    def getFedVersionMajorId(self): return _AccessDb.AccessDb_getFedVersionMajorId(self)
    def getFedVersionMinorId(self): return _AccessDb.AccessDb_getFedVersionMinorId(self)
    def getConnectionVersionMajorId(self): return _AccessDb.AccessDb_getConnectionVersionMajorId(self)
    def getConnectionVersionMinorId(self): return _AccessDb.AccessDb_getConnectionVersionMinorId(self)
    def getDcuInfoVersionMajorId(self): return _AccessDb.AccessDb_getDcuInfoVersionMajorId(self)
    def getDcuInfoVersionMinorId(self): return _AccessDb.AccessDb_getDcuInfoVersionMinorId(self)
    def getDcuPsuMapVersionMajorId(self): return _AccessDb.AccessDb_getDcuPsuMapVersionMajorId(self)
    def getDcuPsuMapVersionMinorId(self): return _AccessDb.AccessDb_getDcuPsuMapVersionMinorId(self)
    def getAnalysisVersionMapPointerId(self): return _AccessDb.AccessDb_getAnalysisVersionMapPointerId(self)
    def getMaskVersionMajorId(self): return _AccessDb.AccessDb_getMaskVersionMajorId(self)
    def getMaskVersionMinorId(self): return _AccessDb.AccessDb_getMaskVersionMinorId(self)
    def getDownloadFec(self): return _AccessDb.AccessDb_getDownloadFec(self)
    def getDownloadFed(self): return _AccessDb.AccessDb_getDownloadFed(self)
    def getDownloadConnection(self): return _AccessDb.AccessDb_getDownloadConnection(self)
    def getDownloadPsu(self): return _AccessDb.AccessDb_getDownloadPsu(self)
    def getDownloadDetId(self): return _AccessDb.AccessDb_getDownloadDetId(self)
    def getCheckBadPll(self): return _AccessDb.AccessDb_getCheckBadPll(self)
    def getCheckMissingDevices(self): return _AccessDb.AccessDb_getCheckMissingDevices(self)
    def getCheckMissingFedChannels(self): return _AccessDb.AccessDb_getCheckMissingFedChannels(self)
    def getCheckFedConnection(self): return _AccessDb.AccessDb_getCheckFedConnection(self)
    def getStripListName(self): return _AccessDb.AccessDb_getStripListName(self)
    def getDisableStrips(self): return _AccessDb.AccessDb_getDisableStrips(self)
    def getUploadFeds(self): return _AccessDb.AccessDb_getUploadFeds(self)
    def getUploadFecs(self): return _AccessDb.AccessDb_getUploadFecs(self)
    def getUploadConnections(self): return _AccessDb.AccessDb_getUploadConnections(self)
    def getPartition(self): return _AccessDb.AccessDb_getPartition(self)
    def getRunVector(self): return _AccessDb.AccessDb_getRunVector(self)
    def getPsuVector(self): return _AccessDb.AccessDb_getPsuVector(self)
    def getMapInfo(self): return _AccessDb.AccessDb_getMapInfo(self)
    def getDeviceVector(self): return _AccessDb.AccessDb_getDeviceVector(self)
    def getConnectionVector(self): return _AccessDb.AccessDb_getConnectionVector(self)
    def getFedVector(self): return _AccessDb.AccessDb_getFedVector(self)
    def DelayModule(self, *args): return _AccessDb.AccessDb_DelayModule(self, *args)
    def DelayDetIds(self, *args): return _AccessDb.AccessDb_DelayDetIds(self, *args)
    __swig_destroy__ = _AccessDb.delete_AccessDb
    __del__ = lambda self : None;
AccessDb_swigregister = _AccessDb.AccessDb_swigregister
AccessDb_swigregister(AccessDb)

# This file is compatible with both classic and new-style classes.


